const jokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call fake spaghetti? An impasta!",
    "Why did the bicycle fall over? It was two-tired.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why was the math book sad? It had too many problems.",
    "Why are ghosts bad at lying? Because they are too transparent.",
    "What did one wall say to the other wall? I’ll meet you at the corner.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What’s orange and sounds like a parrot? A carrot!",
    "Why was the computer cold? It left its Windows open!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why don't eggs tell jokes? They might crack up.",
    "How do you organize a space party? You planet.",
    "What kind of shoes do ninjas wear? Sneakers.",
    "Why did the coffee file a police report? It got mugged.",
    "How do you make a tissue dance? Put a little boogie in it.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "What do you call a fish with no eyes? Fsh.",
    "Why did the M&M go to school? Because it wanted to be a Smartie.",
    "Why can’t you give Elsa a balloon? Because she’ll let it go.",
    "How do you catch a squirrel? Climb a tree and act like a nut.",
    "Why was the belt arrested? For holding up pants!",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the cookie go to the hospital? Because it felt crummy.",
    "Why was the broom late? It swept in.",
    "What do you call cheese that isn’t yours? Nacho cheese.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why did the cow go to space? To see the Milky Way.",
    "Why don’t you play cards in the jungle? Too many cheetahs.",
    "What do you call a can opener that doesn’t work? A can’t opener.",
    "Why did the photo go to jail? It was framed.",
    "Why don’t skeletons ever go trick or treating? Because they have no body to go with.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "How does a penguin build its house? Igloos it together.",
    "Why do ducks have feathers? To cover their butt quacks.",
    "What time is it when the clock strikes 13? Time to get a new clock.",
    "Why don’t some fish play basketball? They’re afraid of the net.",
    "How do you find Will Smith in the snow? Look for fresh prints.",
    "What’s brown and sticky? A stick.",
    "Why did the golfer bring extra socks? In case he got a hole in one.",
    "Why did the mushroom go to the party alone? Because he's a fungi.",
    "Why don’t elephants use computers? They're afraid of the mouse.",
    "Why are frogs so happy? They eat whatever bugs them.",
    "What kind of music do mummies listen to? Wrap music.",
    "What do you call an alligator in a vest? An investigator.",
    "Why are fish so smart? Because they live in schools.",
    "What do you get when you cross a snowman with a dog? Frostbite.",
    "Why can’t your nose be 12 inches long? Because then it would be a foot.",
    "Why don’t ants get sick? Because they have tiny ant-bodies.",
    "What do you call a factory that makes good products? A satisfactory.",
    "Why did the banana go to the doctor? It wasn’t peeling well.",
    "Why can’t you trust stairs? They’re always up to something.",
    "What did the zero say to the eight? Nice belt!",
    "How does a vampire start a letter? Tomb it may concern.",
    "What do you call a dog magician? A labracadabrador.",
    "Why are skeletons so calm? Because nothing gets under their skin.",
    "What kind of car does a sheep drive? A lamborghini.",
    "Why did the student eat his homework? Because the teacher told him it was a piece of cake.",
    "How do cows stay up to date? They read the moos-paper.",
    "Why are teddy bears never hungry? They are always stuffed.",
    "Why did the music teacher go to jail? Because she got caught with sharp notes.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why did the tree go to therapy? It had too many knots.",
    "Why did the orange stop? It ran out of juice.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why don’t oysters donate to charity? Because they are shellfish.",
    "How do you know if a vampire is sick? By his coffin.",
    "Why are pirates such bad singers? They can’t hit the high seas.",
    "Why don’t cows have money? Because the farmers milk them dry.",
    "What kind of key opens a banana? A monkey.",
    "Why did the balloon go near the needle? It wanted to be a pop star.",
    "How do you fix a broken tomato? With tomato paste.",
    "What kind of tree fits in your hand? A palm tree.",
    "Why did the golfer bring extra pants? In case he got a hole in one.",
    "Why did the bicycle fall over? It was two tired.",
    "How do you organize a space party? You planet.",
    "What do you call a pig that does karate? A pork chop.",
    "Why did the apple stop running? It ran out of juice.",
    "What did one hat say to the other? Stay here, I’m going on ahead.",
    "Why can’t a nose be 12 inches long? Because then it would be a foot.",
    "Why did the strawberry cry? Because it was in a jam.",
    "What’s a skeleton’s least favorite room? The living room.",
    "Why don’t dogs make good dancers? They have two left feet.",
    "What do you call an illegally parked frog? Toad.",
    "What do you call a group of musical whales? An orca-stra.",
    "How do cows do math? They use a cow-culator.",
    "Why did the chicken go to the seance? To talk to the other side.",
    "What’s a ghost’s favorite dessert? I scream.",
    "Why can’t you play hide and seek with mountains? They always peak.",
    "What did the big flower say to the little flower? Hey, bud!",
    "Why did the vampire need mouthwash? Because he had bat breath.",
    "What do you call an elephant that doesn’t matter? An irrelephant."
  ];
  
  console.log(jokes);
  