const jokes = [
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "Why do Java developers wear glasses? Because they don’t see sharp.",
    "A SQL query walks into a bar, walks up to two tables, and asks, 'Can I join you?'",
    "Why do programmers hate nature? It has too many bugs.",
    "Why do Python programmers prefer the dark? Because they don’t want to deal with indentation errors.",
    "What do you call a programmer from Finland? Nerdic.",
    "Why did the developer go broke? Because he used up all his cache.",
    "There are only two hard things in computer science: cache invalidation and naming things.",
    "I told my girlfriend she was drawing her eyebrows too high. She looked surprised.",
    "Why do women make terrible programmers? Because they can’t use the backspace key.",
    "What do you get when you cross a bad joke with a joke about coding? A syntax error.",
    "How many programmers does it take to change a light bulb? None. It’s a hardware problem.",
    "Why did the programmer quit his job? Because he didn’t get arrays.",
    "What do you call a gay guy who’s into programming? A code warrior.",
    "Why don’t programmers like to play hide and seek? Because good luck hiding when they can just debug you.",
    "Why did the computer keep freezing? It left its Windows open.",
    "How do you comfort a JavaScript bug? You console it.",
    "Why do programmers prefer iOS development? Because they can’t handle Java beans.",
    "I’m on a whiskey diet. I’ve lost three days already.",
    "Why did the coder get kicked out of school? He kept trying to take classes.",
    "What did the gay programmer say? 'It’s not just a phase; it’s a function!'",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 equals Dec 25.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "How do you organize a space party? You planet.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "What do you call a pile of cats? A meowtain.",
    "I told my computer I needed a break, and now it won’t stop sending me beach wallpapers.",
    "Why was the math book sad? Because it had too many problems.",
    "I’m reading a book on anti-gravity. It’s impossible to put down!",
    "Why did the coffee file a police report? It got mugged.",
    "What do you call fake spaghetti? An impasta!",
    "I used to play piano by ear, but now I use my hands.",
    "Why can’t you give Elsa a balloon? Because she will let it go.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why did the cookie cry? Because its mother was a wafer (wafer) too long.",
    "What did the janitor say when he jumped out of the closet? 'Supplies!'",
    "Why did the stadium get hot after the game? All of the fans left.",
    "Why don’t scientists trust atoms? Because they make up everything.",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Why was the computer cold? It left its Windows open.",
    "What did one wall say to the other wall? 'I’ll meet you at the corner.'",
    "Why are ghosts bad liars? Because you can see right through them!",
    "What do you call an alligator in a vest? An investigator.",
    "Why did the math teacher break up with the biology teacher? There was no chemistry.",
    "What did the duck say when it bought lipstick? 'Put it on my bill!'",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "Why can’t you hear a pterodactyl go to the bathroom? Because the 'P' is silent.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the gym close down? It just didn’t work out.",
    "Why was the belt arrested? For holding up a pair of pants!",
    "What do you call a fish with no eyes? Fsh.",
    "Why did the picture go to jail? Because it was framed.",
    "Why did the frog take the bus to work? His car got toad away.",
    "Why did the snowman call for a police officer? He was assaulted!",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why did the man run around his bed? Because he was trying to catch up on his sleep!",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What do you call a can opener that doesn’t work? A can’t opener!",
    "I used to be a baker, but I couldn’t make enough dough.",
    "Why did the computer go to the doctor? It had a virus!",
    "Why did the orange stop? It ran out of juice.",
    "Why don’t programmers like nature? It has too many bugs.",
    "What do you get when you cross a snowman with a vampire? Frostbite.",
    "What did the fish say when it hit the wall? Dam!",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels!",
    "What do you call a lazy kangaroo? A pouch potato.",
    "Why did the mushroom go to the party? Because he was a fungi!",
    "What’s brown and sticky? A stick.",
    "What did the left eye say to the right eye? Between you and me, something smells!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why do bicycles fall over? Because they are two-tired!",
    "How do you make a tissue dance? You put a little boogie in it.",
    "What do you call an elephant that doesn’t matter? An irrelephant.",
    "Why did the bee get married? Because he found his honey.",
    "What’s orange and sounds like a parrot? A carrot!",
    "Why was the computer cold? It left its Windows open.",
    "What do you call a belt made out of watches? A waist of time."
];





document.getElementById("btn").onclick= generateJokes
function generateJokes(){
    let index = Math.floor(Math.random()*jokes.length)
    return document.getElementById("box").innerHTML = `${jokes[index]}`
}
  

